# Generated by Django 5.2 on 2025-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flasky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.CharField(choices=[('tuf', 'TUF'), ('zephyrus', 'Zephyrus'), ('zenbook', 'Zenbook'), ('strix', 'Strix'), ('vivobook', 'Vivobook')], default='tuf', max_length=20),
        ),
    ]
