# Generated by Django 5.2 on 2025-05-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flasky', '0002_feedback_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
    ]
